spring:
  datasource:
    url: jdbc:mysql://localhost:3306/brazilgreen?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: CRbygAtdWGPsFuQZ6HyvFxwkkSxRPe
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      dll-auto: create
    properties:
      '[hibernate.format_sql]': true